[package]
name = "mill-rpc-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Proc macros for Mill-RPC service definitions"
documentation = "https://docs.rs/mill-rpc-macros"
homepage = "https://github.com/citadel-tech/mill-io"
repository = "https://github.com/citadel-tech/mill-io"
readme = "../README.md"
keywords = ["rpc", "mill-io", "macros", "proc-macro", "codegen"]
categories = ["network-programming"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
