[workspace]
members = [
    "mill-io",
    "mill-net",
    "mill-rpc",
    "mill-rpc/mill-rpc-core",
    "mill-rpc/mill-rpc-macros",
]
resolver = "2"

[workspace.package]
version = "2.0.1"
authors = ["Citadel-tech", "Mohamed Emad <hulxxv@gmail.com>"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.70"

[workspace.dependencies]
mio = { version = "1.1.0", features = ["os-poll", "net"] }
lock_freedom = "0.1.1"

mill-io = { path = "mill-io" }
